spring:
  sql:
    init:
      mode: always
      data-locations: classpath:/db/data.sql
      schema-locations: classpath:/db/schema.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:~/meal_voting_test
    username: sa
    password: password
  h2:
    console.enabled: true
